#set page(paper: "a4", margin: 2cm)
#set text(font: "Liberation Sans", size: 12pt)

#align(center)[
  #text(size: 20pt, weight: "bold")[
    Test Document
  ]
]

== Test Section

This is a test document generated from a string template.

== Features

- Simple and clean API
- Remote FaaS execution
- Support for media files and options
- Correlation ID tracking for debugging

#v(1em)

#align(center)[
  _Generated by typst-pdf-generator-go_
]
