#set page(paper: "a4", margin: 2cm)
#set text(font: "Liberation Sans", size: 11pt)

#align(center)[
  #text(size: 24pt, weight: "bold")[
    Integration Test Document
  ]

  #v(1em)

  #text(size: 14pt, style: "italic")[
    Generated by typst-pdf-generator-go
  ]
]

#v(2em)

= Introduction

This document is generated as part of the integration test suite for the
typst-pdf-generator-go client library.

== Test Details

- *Test Date*: #datetime.today().display()
- *Template Type*: File-based template
- *Purpose*: Integration testing with visual output

== Features Tested

+ Remote FaaS execution
+ PDF generation from file templates
+ Response metadata tracking
+ File persistence verification

= Content Sections

== Lorem Ipsum

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris.

== Sample Code Block

```go
package main

import "fmt"

func main() {
    fmt.Println("Hello from Typst!")
}
```

== Mathematical Formula

The quadratic formula: $ x = (-b plus.minus sqrt(b^2 - 4a c)) / (2a) $

== Table Example

#table(
  columns: 3,
  [Feature], [Status], [Notes],
  [Template Support], [✓], [Working],
  [Media Files], [✓], [Images, fonts, JSON],
  [Options], [✓], [PPI, format],
  [Error Handling], [✓], [Detailed errors],
)

= Graphics Example

#align(center)[
  #rect(
    width: 80%,
    height: 3cm,
    fill: gradient.linear(..color.map.rainbow),
    stroke: 1pt,
  )

  _Gradient test_
]

#pagebreak()

= Second Page

This is a multi-page document to test page handling.

== More Content

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

#v(1fr)

#align(center)[
  #line(length: 50%)

  _End of Test Document_
]
